# Generated by Django 3.1.1 on 2020-10-15 12:21

from django.db import migrations, models

import utils.base_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(verbose_name='上次更新时间')),
                ('content', utils.base_models.RichTextField()),
                ('department', models.CharField(db_index=True, max_length=100, verbose_name='部门名')),
                ('doc_id', models.PositiveIntegerField(db_index=True, default=0, unique=True, verbose_name='公文通id')),
                ('category', models.CharField(db_index=True, default='', max_length=20, verbose_name='类别')),
            ],
            options={
                'ordering': ('-last_update_time',),
            },
        ),
    ]
