# Generated by Django 3.1.1 on 2020-10-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysOptions',
            fields=[
                ('key', models.TextField(choices=[('swiper', 'Swiper')], primary_key=True, serialize=False, unique=True)),
                ('value', models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
