# Generated by Django 3.1.1 on 2020-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='szu_id',
            field=models.IntegerField(default=0, help_text='在深大系统中的id'),
        ),
        migrations.AlterField(
            model_name='building',
            name='szu_id',
            field=models.IntegerField(db_index=True, help_text='在深大系统中的id'),
        ),
        migrations.AlterField(
            model_name='room',
            name='power_data',
            field=models.JSONField(default=dict, verbose_name='电量记录'),
        ),
    ]
