# Generated by Django 3.1.1 on 2020-10-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0002_auto_20201017_2335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('campus', 'building', 'room_no'), name='unique_room'),
        ),
    ]
