# Generated by Django 3.1.1 on 2020-10-21 15:40

from django.db import migrations
import utils.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='config',
            field=utils.base_models.JSONSchemaField(default={'dormitory': {'areaName': '', 'buildingID': '', 'buildingName': '', 'campusName': '', 'roomNo': None, 'subscribe': False}}, help_text='用户设置'),
        ),
    ]
