# Generated by Django 3.1.1 on 2020-10-28 17:00

from django.db import migrations
import user.models
import utils.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201021_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='config',
            field=utils.base_models.JSONSchemaField(default=user.models.default_config, help_text='用户设置'),
        ),
    ]
